# Generated by Django 5.1.7 on 2026-08-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_rights',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Супер-администратор'), ('director', 'Директор'), ('deputy_director', 'Заместитель директора'), ('administrator', 'Администратор'), ('doctor', 'Врач'), ('accountant', 'Бухгалтер')], default='administrator', max_length=20),
        ),
    ]
